Add small sleep to retryment for GoneError
To fix unstable tests:

    TestWatchNamespaces#test_0012_namespace watch retries when 410 Gone errors are encountered:
    NoMethodError: undefined method `>=' for nil:NilClass
        test/plugin/test_watch_namespaces.rb:250:in `block (3 levels) in <class:TestWatchNamespaces>'
        test/plugin/test_watch_namespaces.rb:241:in `block (2 levels) in <class:TestWatchNamespaces>'
        test/plugin/test_watch_namespaces.rb:240:in `block in <class:TestWatchNamespaces>'

    TestWatchPods#test_0013_pod watch retries when 410 Gone errors are encountered:
    NoMethodError: undefined method '>=' for nil
        test/plugin/test_watch_pods.rb:360:in 'block (3 levels) in <class:TestWatchPods>'
        test/plugin/test_watch_pods.rb:351:in 'block (2 levels) in <class:TestWatchPods>'
        test/plugin/test_watch_pods.rb:350:in 'block in <class:TestWatchPods>'

It appears that the cause could be the infinite loop without
any sleep when GoneError occurs.

Signed-off-by: Daijiro Fukuda <fukuda@clear-code.com>